version: '3.8'

services:
  app:
    image: marley2022/ihome-agents:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./research_stocks/src/research_stocks:/app
      - ./output:/app/output
    working_dir: /app
    command: [ "sleep", "3600" ]
    restart: unless-stopped
